message(STATUS "Extern: bzip2 1.0.6")

set(bzip2_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/local")
set(bzip2_INCLUDE_DIR "${bzip2_INSTALL_DIR}/include")
set(bzip2_LIBRARY_DIR "${bzip2_INSTALL_DIR}/lib")

ExternalProject_Add(extern_bzip2
	PREFIX "${CMAKE_CURRENT_BINARY_DIR}/bzip2"
	SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src_extern/bzip2-1.0.6"
	# configure
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX=${bzip2_INSTALL_DIR}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_C_FLAGS_DEBUG=${CMAKE_C_FLAGS_DEBUG}
		-DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}
		-DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}
	# install
	INSTALL_DIR ${bzip2_INSTALL_DIR}
	)

add_library(bzip2 STATIC IMPORTED)
set_target_properties(bzip2
	PROPERTIES
		IMPORTED_LOCATION
			${bzip2_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}bzip2${CMAKE_STATIC_LIBRARY_SUFFIX}
	)
add_dependencies(bzip2 extern_bzip2)
include_directories(${bzip2_INCLUDE_DIR})

