message(STATUS "Extern: libtcd 2.2.5")

set(tcd_INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/local")
set(tcd_INCLUDE_DIR "${tcd_INSTALL_DIR}/include")
set(tcd_LIBRARY_DIR "${tcd_INSTALL_DIR}/lib")

ExternalProject_Add(extern_tcd
	PREFIX "${CMAKE_CURRENT_BINARY_DIR}/tcd"
	SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src_extern/libtcd-2.2.5"
	# configure
	CMAKE_ARGS
		-DCMAKE_INSTALL_PREFIX=${tcd_INSTALL_DIR}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_C_FLAGS_DEBUG=${CMAKE_C_FLAGS_DEBUG}
		-DCMAKE_C_FLAGS_RELEASE=${CMAKE_C_FLAGS_RELEASE}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}
		-DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}
	# install
	INSTALL_DIR ${tcd_INSTALL_DIR}
	)

add_library(tcd STATIC IMPORTED)
set_target_properties(tcd
	PROPERTIES
		IMPORTED_LOCATION
			${tcd_LIBRARY_DIR}/${CMAKE_STATIC_LIBRARY_PREFIX}tcd${CMAKE_STATIC_LIBRARY_SUFFIX}
	)
add_dependencies(tcd extern_tcd)
include_directories(${tcd_INCLUDE_DIR})

